
export const characterSrc: Record<string, { src: string }> = {
    abyss: { src: "/girlfriend/anime/Abyss/abyss.png" },
    acheron: { src: "/girlfriend/anime/Acheron/acheron.png" },
    aerith: { src: "/girlfriend/anime/Aerith/aerith.png" },
    ahri: { src: "/girlfriend/anime/Ahri/ahri.png" },
    ahsoka: { src: "/girlfriend/anime/Ahsoka Tano/ahsoka.png" },
    ako: { src: "/girlfriend/anime/Ako/ako.png" },
    albedo: { src: "/girlfriend/anime/Albedo/albedo.png" },
    alexia: { src: "/girlfriend/anime/Alexia/alexia.png" },
    alexiaMidgar: { src: "/girlfriend/anime/Alexia Midgar/alexia.png" },
    alice: { src: "/girlfriend/anime/Alice/alice.png" },
    aliceZuberg: { src: "/girlfriend/anime/Alice Zuberg/alice.png" },
    alpha: { src: "/girlfriend/anime/Alpha/alpha.png" },
    aqua: { src: "/girlfriend/anime/aqua/aqua.png" },
    astoria: { src: "/girlfriend/anime/Artoria/marina.png" },
    asadaShino: { src: "/girlfriend/anime/Asada Shino/asada.png" },
    astolfo: { src: "/girlfriend/anime/Astolfo/astolfo.png" },
    asuna: { src: "/girlfriend/anime/asuna/asuna.png" },
    asunaCopy: { src: "/girlfriend/anime/Asuna copy/asuna.png" },
    ayaka: { src: "/girlfriend/anime/Ayaka/ayaka.png" },
    ayaseMomo: { src: "/girlfriend/anime/Ayase Momo/ayase.png" },
    blake: { src: "/girlfriend/anime/Blake Belladona/blake.png" },
    blue: { src: "/girlfriend/anime/Blue Archive/blue.png" },
    chaHaeIn2: { src: "/girlfriend/anime/Cha Hae In/cha.png" },
    chizuru: { src: "/girlfriend/anime/Chizuru/chizuru.png" },
    cinderella: { src: "/girlfriend/anime/Cinderella/cinderella.png" },
    clorinde: { src: "/girlfriend/anime/Clorinde/clorinde.png" },
    cynthia: { src: "/girlfriend/anime/Cynthia/cynthia.png" },
    demon: { src: "/girlfriend/anime/Demon/demon.png" },
    ellenJoe: { src: "/girlfriend/anime/Ellen Joe/ellen.png" },
    elsa: { src: "/girlfriend/anime/Elsa/elsa.png" },
    emilia: { src: "/girlfriend/anime/Emilia/emilia.png" },
    erzaScarlet: { src: "/girlfriend/anime/Erza Scarlet/erza.png" },
    esdeath: { src: "/girlfriend/anime/Esdeath/esdeath.png" },
    ethereal: { src: "/girlfriend/anime/Ethereal/ethereal.png" },
    evileye: { src: "/girlfriend/anime/Evileye/evileye.png" },
    firefly: { src: "/girlfriend/anime/Firefly/firefly.png" },
    frieren: { src: "/girlfriend/anime/Frieren/frieren.png" },
    furina: { src: "/girlfriend/anime/Furina/furina.png" },
    ganyu: { src: "/girlfriend/anime/ganyu/ganyu.png" },
    gifs: { src: "/girlfriend/anime/gifs/gifs.png" },
    hina: { src: "/girlfriend/anime/Hina/hina.png" },
    hinata: { src: "/girlfriend/anime/Hinata/hinata.png" },
    jean: { src: "/girlfriend/anime/Jean/jean.png" },
    jeanne: { src: "/girlfriend/anime/Jeanne/jeanne.png" },
    jeanneAlter: { src: "/girlfriend/anime/Jeanne Alter/jeanne alter.png" },
    jessie: { src: "/girlfriend/anime/Jessie/jessie.png" },
    karin: { src: "/girlfriend/anime/Karin/Karin.jpg" },
    katara: { src: "/girlfriend/anime/katara/katara.jpg" },
    keqing: { src: "/girlfriend/anime/Keqing/Keqing.jpg" },
    kiana: { src: "/girlfriend/anime/Kiana/Kiana.jpg" },
    kurumi: { src: "/girlfriend/anime/Kurumi/Kurumi.jpg" },
    lanYan: { src: "/girlfriend/anime/Lan Yan/Lan Yan.jpg" },
    leafa: { src: "/girlfriend/anime/Leafa/Leafa.jpg" },
    megumin: { src: "/girlfriend/anime/megumin/megumin.jpg" },
    roxy: { src: "/girlfriend/anime/roxy/roxy.jpg" },
    two: { src: "/girlfriend/anime/two/two.jpg" },
    aisha: { src: "/girlfriend/anime/Aisha.jpg" },
    akira: { src: "/girlfriend/anime/Akira.jpg" },
    amy: { src: "/girlfriend/anime/Amy.jpg" },
    aquaM: { src: "/girlfriend/anime/AquaM.jpeg" },
    aquaM2: { src: "/girlfriend/anime/AquaM2.jpeg" },
    asuna3: { src: "/girlfriend/anime/Asuna3.jpeg" },
    asunaButton: { src: "/girlfriend/anime/AsunaButton.png" },
    boa: { src: "/girlfriend/anime/Boa.jpeg" },
    chihiya: { src: "/girlfriend/anime/Chihiya.jpeg" },
    chitoge: { src: "/girlfriend/anime/Chitoge.jpeg" },
    darkMagicianGirlie: { src: "/girlfriend/anime/DarkMagicianGirlie.jpg" },
    darkness: { src: "/girlfriend/anime/Darkness.jpeg" },
    elle: { src: "/girlfriend/anime/elle.png" },
    eru: { src: "/girlfriend/anime/Eru.jpeg" },
    goddess: { src: "/girlfriend/anime/goddess.jpeg" },
    haruhi: { src: "/girlfriend/anime/Haruhi.jpeg" },
    katie: { src: "/girlfriend/anime/Katie.png" },
    kittie: { src: "/girlfriend/anime/Kittie.jpeg" },
    lilly: { src: "/girlfriend/anime/Lilly.png" },
    lucy: { src: "/girlfriend/anime/Lucy.jpeg" },
    maka: { src: "/girlfriend/anime/Maka.jpeg" },
    marie: { src: "/girlfriend/anime/Marie.jpeg" },
    mia: { src: "/girlfriend/anime/Mia.jpg" },
    mikasa: { src: "/girlfriend/anime/Mikasa.jpeg" },
    miko: { src: "/girlfriend/anime/Miko.jpeg" },
    mina: { src: "/girlfriend/anime/Mina.png" },
    mira: { src: "/girlfriend/anime/Mira/jane.jpeg" },
    misty: { src: "/girlfriend/anime/Misty.png" },
    misuna: { src: "/girlfriend/anime/Misuna.jpg" },
    peach: { src: "/girlfriend/anime/Peach.jpg" },
    peggingmeg: { src: "/girlfriend/anime/peggingmeg.jpg" },
    pia: { src: "/girlfriend/anime/Pia.jpeg" },
    pochi: { src: "/girlfriend/anime/Pochi.jpg" },
    reina: { src: "/girlfriend/anime/Reina.jpg" },
    sai: { src: "/girlfriend/anime/Sai.jpg" },
    sara: { src: "/girlfriend/anime/Sara.jpg" },
    scarlett: { src: "/girlfriend/anime/Scarlett.jpeg" },
    tinkerbell: { src: "/girlfriend/anime/TinkerBell.png" },
    toph: { src: "/girlfriend/anime/Toph.jpg" },
    umbreon: { src: "/girlfriend/anime/Umbreon.jpg" },
    wiz: { src: "/girlfriend/anime/Wiz.jpeg" },
    yuki: { src: "/girlfriend/anime/Yuki.png" },
    yuni: { src: "/girlfriend/anime/Yuni.jpeg" },
};

